# Generated by Django 2.1.5 on 2019-02-07 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20190123_1552'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
