# Generated by Django 2.1.5 on 2019-01-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gitlink',
            field=models.CharField(default='www', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='name1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='tech',
            field=models.CharField(default='tech1', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.TextField(),
        ),
    ]
